---
to: <%= project %>/README.md
---
# <%= project %>

Project automatically generated by https://github.com/my0n/hygen-templates.

# TODO

<% if (ci.includes('Dependabot')) { -%>
- [ ] Configure [.github/dependabot.yml](.github/dependabot.yml)
<% } -%>
